# Generated by Django 2.2.1 on 2019-05-20 11:36

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('image', stdimage.models.StdImageField(upload_to='items_for_sale_images')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
