# Generated by Django 2.2.1 on 2019-05-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forSale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsforsale',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
