# Generated by Django 2.2.1 on 2019-05-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forSale', '0002_auto_20190520_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsforsale',
            name='price',
            field=models.IntegerField(help_text='Use the following format: 1000 for $10.00'),
        ),
    ]
